# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pushing to github

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Prettier format check
        run: npm run format:check

      - name: Project lint
        run: npm lint

      - name: Run tests
        run: npm test
        working-directory: server
